INSERT INTO COUNTRY (country_name, country_code) VALUES ('Turkey', 'TR');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('United States', 'US');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Japan', 'JP');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Germany', 'DE');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Brazil', 'BR');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Australia', 'AU');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Canada', 'CA');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('India', 'IN');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('France', 'FR');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('South Korea', 'KR');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('United Kingdom', 'GB');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Italy', 'IT');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Spain', 'ES');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Mexico', 'MX');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Russia', 'RU');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('China', 'CN');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Netherlands', 'NL');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Sweden', 'SE');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Norway', 'NO');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Denmark', 'DK');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Finland', 'FI');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Poland', 'PL');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Switzerland', 'CH');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Belgium', 'BE');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Argentina', 'AR');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('South Africa', 'ZA');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('New Zealand', 'NZ');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Saudi Arabia', 'SA');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Indonesia', 'ID');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Egypt', 'EG');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Thailand', 'TH');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Ukraine', 'UA');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Pakistan', 'PK');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Vietnam', 'VN');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Philippines', 'PH');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Malaysia', 'MY');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Austria', 'AT');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Portugal', 'PT');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Ireland', 'IE');
INSERT INTO COUNTRY (country_name, country_code) VALUES ('Singapore', 'SG');
