INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (23, 'Chill & Unwind', 'A mix of funk', '2020-09-29', 'playlist_1.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (88, 'Weekend Vibes', 'A mix of electronic', '2023-12-31', 'playlist_2.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (66, 'Golden Groove', 'A mix of latin', '2020-10-25', 'playlist_3.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (92, 'Flow State', 'A mix of rock', '2023-11-15', 'playlist_4.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (80, 'Soulful Sundays', 'A mix of classical', '2020-01-13', 'playlist_5.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Smooth Sailing', 'A mix of punk', '2021-08-22', 'playlist_6.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (40, 'City Lights', 'A mix of funk', '2024-06-21', 'playlist_7.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (83, 'Beat Drop', 'A mix of soul', '2021-06-30', 'playlist_8.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (12, 'Whispering Waves', 'A mix of folk', '2021-04-24', 'playlist_9.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (91, 'Cascade Waves', 'A mix of metal', '2021-10-02', 'playlist_10.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (13, 'Floating Free', 'A mix of pop', '2025-04-17', 'playlist_11.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (41, 'Soulful Sundays', 'A mix of ambient', '2022-04-02', 'playlist_12.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (13, 'High Tide', 'A mix of soul', '2024-12-06', 'playlist_13.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (71, 'Twilight Tones', 'A mix of jazz', '2022-03-26', 'playlist_14.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (5, 'Throwback Jams', 'A mix of ambient', '2024-06-06', 'playlist_15.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (84, 'City Lights', 'A mix of classical', '2020-08-06', 'playlist_16.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (91, 'Study Focus', 'A mix of electronic', '2023-11-21', 'playlist_17.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (17, 'Velvet Lounge', 'A mix of electronic', '2021-01-31', 'playlist_18.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (16, 'Beat Drop', 'A mix of r&b', '2020-09-26', 'playlist_19.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (99, 'Hometown Heroes', 'A mix of pop', '2020-09-18', 'playlist_20.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (12, 'Cosmic Drift', 'A mix of blues', '2020-07-01', 'playlist_21.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (15, 'Mystic Rhythms', 'A mix of world', '2022-10-01', 'playlist_22.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (92, 'Throwback Jams', 'A mix of world', '2021-10-11', 'playlist_23.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Moonlit Melodies', 'A mix of folk', '2022-04-15', 'playlist_24.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (87, 'Secret Stash', 'A mix of country', '2021-02-07', 'playlist_25.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (20, 'Electric Sunset', 'A mix of folk', '2023-12-17', 'playlist_26.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (7, 'Heavy Rotation', 'A mix of world', '2023-12-20', 'playlist_27.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (2, 'Cascade Waves', 'A mix of world', '2023-11-03', 'playlist_28.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'City Lights', 'A mix of metal', '2020-08-18', 'playlist_29.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (20, 'Velvet Dusk', 'A mix of reggae', '2025-04-28', 'playlist_30.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (90, 'Heartbeat Highway', 'A mix of dance', '2022-09-09', 'playlist_31.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (76, 'High Tide', 'A mix of latin', '2025-05-07', 'playlist_32.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (84, 'Neon Canvas', 'A mix of soul', '2021-11-25', 'playlist_33.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (69, 'Vintage Vibes', 'A mix of folk', '2025-01-20', 'playlist_34.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (16, 'Twilight Tones', 'A mix of pop', '2023-11-02', 'playlist_35.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (99, 'Hometown Heroes', 'A mix of funk', '2024-01-20', 'playlist_36.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (26, 'Study Focus', 'A mix of soul', '2023-04-27', 'playlist_37.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (56, 'Floating Free', 'A mix of soul', '2024-04-16', 'playlist_38.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (63, 'Funky Fusion', 'A mix of dance', '2020-05-31', 'playlist_39.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (25, 'Neon Nights', 'A mix of ambient', '2022-09-19', 'playlist_40.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (39, 'Summer Heat', 'A mix of reggae', '2020-01-15', 'playlist_41.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (37, 'Sunshine Serenade', 'A mix of blues', '2020-05-05', 'playlist_42.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (97, 'Chill & Unwind', 'A mix of dance', '2023-08-29', 'playlist_43.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (62, 'Starlit Skies', 'A mix of pop', '2021-06-04', 'playlist_44.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (33, 'Heartbeat Highway', 'A mix of reggae', '2024-03-18', 'playlist_45.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (60, 'Electric Sunset', 'A mix of soul', '2023-11-15', 'playlist_46.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (32, 'High Tide', 'A mix of hip-hop', '2021-01-22', 'playlist_47.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (5, 'Funky Fusion', 'A mix of dance', '2020-10-16', 'playlist_48.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (80, 'Sonic Sunrise', 'A mix of indie', '2022-03-27', 'playlist_49.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (55, 'Soulful Sundays', 'A mix of classical', '2022-05-04', 'playlist_50.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (30, 'Ember Glow', 'A mix of r&b', '2021-09-29', 'playlist_51.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (96, 'Midnight Drive', 'A mix of funk', '2021-11-17', 'playlist_52.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (13, 'Rooftop Rhythms', 'A mix of pop', '2020-04-30', 'playlist_53.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (65, 'Neon Nights', 'A mix of punk', '2024-05-25', 'playlist_54.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (8, 'Acoustic Mornings', 'A mix of country', '2020-04-05', 'playlist_55.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (28, 'Morning Dew', 'A mix of hip-hop', '2020-10-01', 'playlist_56.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (7, 'Vintage Vibes', 'A mix of indie', '2024-04-26', 'playlist_57.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (4, 'Weekend Vibes', 'A mix of funk', '2024-04-27', 'playlist_58.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (49, 'Rooftop Rhythms', 'A mix of indie', '2020-05-02', 'playlist_59.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (2, 'Desert Winds', 'A mix of dance', '2023-11-16', 'playlist_60.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (75, 'Smooth Sailing', 'A mix of latin', '2020-04-19', 'playlist_61.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (21, 'Morning Dew', 'A mix of rock', '2021-04-17', 'playlist_62.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (5, 'Mystic Rhythms', 'A mix of hip-hop', '2022-12-21', 'playlist_63.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (90, 'Roaming Beats', 'A mix of metal', '2021-01-02', 'playlist_64.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (69, 'Fresh Finds', 'A mix of funk', '2023-05-01', 'playlist_65.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (20, 'Desert Winds', 'A mix of ambient', '2025-03-26', 'playlist_66.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (72, 'Midnight Drive', 'A mix of latin', '2023-10-11', 'playlist_67.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (26, 'Aurora Beats', 'A mix of classical', '2023-05-27', 'playlist_68.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (16, 'Aurora Beats', 'A mix of electronic', '2025-04-22', 'playlist_69.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Blue Horizon', 'A mix of classical', '2024-08-09', 'playlist_70.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (100, 'Soulful Sundays', 'A mix of funk', '2024-07-07', 'playlist_71.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (26, 'Velvet Dusk', 'A mix of ambient', '2021-05-15', 'playlist_72.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (49, 'Sonic Sunrise', 'A mix of rock', '2020-07-24', 'playlist_73.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'Lush Landscapes', 'A mix of reggae', '2023-01-14', 'playlist_74.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (98, 'Coastal Chill', 'A mix of dance', '2021-12-30', 'playlist_75.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (66, 'Velvet Dusk', 'A mix of pop', '2021-06-08', 'playlist_76.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (47, 'Rooftop Rhythms', 'A mix of hip-hop', '2024-05-07', 'playlist_77.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (13, 'Electric Avenue', 'A mix of pop', '2024-03-02', 'playlist_78.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (50, 'Weekend Vibes', 'A mix of r&b', '2021-08-25', 'playlist_79.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (48, 'Urban Pulse', 'A mix of pop', '2025-02-01', 'playlist_80.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (96, 'Coastal Chill', 'A mix of world', '2022-07-29', 'playlist_81.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (28, 'Cascade Waves', 'A mix of folk', '2023-01-06', 'playlist_82.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (54, 'Sonic Sunrise', 'A mix of pop', '2021-08-25', 'playlist_83.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (82, 'Moonlit Melodies', 'A mix of pop', '2023-11-22', 'playlist_84.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (95, 'Secret Stash', 'A mix of rock', '2022-05-27', 'playlist_85.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (88, 'Summer Heat', 'A mix of country', '2023-04-28', 'playlist_86.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (91, 'Starlit Skies', 'A mix of metal', '2025-04-12', 'playlist_87.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (36, 'Ocean Breeze', 'A mix of pop', '2024-09-22', 'playlist_88.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (15, 'Rooftop Rhythms', 'A mix of classical', '2024-12-11', 'playlist_89.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (13, 'Synthwave Dreams', 'A mix of classical', '2025-01-13', 'playlist_90.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (36, 'Acoustic Mornings', 'A mix of latin', '2022-12-11', 'playlist_91.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (34, 'Neon Nights', 'A mix of dance', '2023-02-12', 'playlist_92.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (65, 'Golden Hour', 'A mix of soul', '2024-05-26', 'playlist_93.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (17, 'Warm Embrace', 'A mix of rock', '2024-10-24', 'playlist_94.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (66, 'Groove Theory', 'A mix of folk', '2020-03-08', 'playlist_95.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (4, 'Vintage Vibes', 'A mix of blues', '2021-07-15', 'playlist_96.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (58, 'Lush Landscapes', 'A mix of dance', '2022-07-27', 'playlist_97.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (99, 'Tranquil Trails', 'A mix of country', '2024-08-25', 'playlist_98.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (20, 'Heavy Rotation', 'A mix of classical', '2020-03-04', 'playlist_99.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (83, 'Ocean Breeze', 'A mix of dance', '2020-10-14', 'playlist_100.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (6, 'Secret Stash', 'A mix of punk', '2022-06-25', 'playlist_101.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (91, 'Synthwave Dreams', 'A mix of metal', '2021-10-23', 'playlist_102.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (62, 'Aurora Beats', 'A mix of indie', '2021-06-05', 'playlist_103.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (93, 'Sonic Sunrise', 'A mix of r&b', '2021-04-13', 'playlist_104.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (48, 'Groove Theory', 'A mix of latin', '2021-07-10', 'playlist_105.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (52, 'Heavy Rotation', 'A mix of rock', '2024-12-23', 'playlist_106.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (57, 'Urban Underground', 'A mix of soul', '2021-01-04', 'playlist_107.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (77, 'Vintage Vibes', 'A mix of r&b', '2020-02-28', 'playlist_108.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (44, 'Serene Strings', 'A mix of classical', '2022-06-20', 'playlist_109.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (80, 'Chill & Unwind', 'A mix of soul', '2023-08-31', 'playlist_110.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (41, 'Groove Theory', 'A mix of punk', '2022-02-21', 'playlist_111.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (38, 'Funky Fusion', 'A mix of country', '2022-05-26', 'playlist_112.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (33, 'Electric Sunset', 'A mix of latin', '2025-02-20', 'playlist_113.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (21, 'Chill & Unwind', 'A mix of dance', '2020-11-02', 'playlist_114.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (18, 'Afterglow', 'A mix of reggae', '2025-04-28', 'playlist_115.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (14, 'Warm Embrace', 'A mix of country', '2022-07-21', 'playlist_116.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (26, 'Soulful Sundays', 'A mix of ambient', '2020-09-23', 'playlist_117.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (50, 'Floating Free', 'A mix of metal', '2024-01-03', 'playlist_118.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (45, 'Serene Strings', 'A mix of ambient', '2024-12-12', 'playlist_119.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (82, 'Morning Dew', 'A mix of classical', '2021-06-16', 'playlist_120.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (15, 'Saturday Morning Jazz', 'A mix of jazz', '2023-04-19', 'playlist_121.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (23, 'Coastal Chill', 'A mix of classical', '2022-05-30', 'playlist_122.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (24, 'Rainy Day Moods', 'A mix of pop', '2024-07-17', 'playlist_123.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (38, 'Tranquil Trails', 'A mix of rock', '2020-11-20', 'playlist_124.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (22, 'Fresh Finds', 'A mix of classical', '2023-10-27', 'playlist_125.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (50, 'Synthwave Dreams', 'A mix of punk', '2020-02-19', 'playlist_126.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (87, 'Moonlit Melodies', 'A mix of metal', '2022-12-02', 'playlist_127.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (58, 'Secret Stash', 'A mix of blues', '2021-05-04', 'playlist_128.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (89, 'Heavy Rotation', 'A mix of r&b', '2024-02-15', 'playlist_129.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (99, 'Energize', 'A mix of dance', '2020-08-29', 'playlist_130.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (84, 'Soul Session', 'A mix of punk', '2022-06-25', 'playlist_131.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (52, 'Serene Strings', 'A mix of funk', '2023-08-08', 'playlist_132.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (99, 'Groove Theory', 'A mix of soul', '2023-09-13', 'playlist_133.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (77, 'Coastal Chill', 'A mix of soul', '2022-05-21', 'playlist_134.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'Midnight Reverie', 'A mix of reggae', '2023-08-21', 'playlist_135.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (52, 'Electric Sunset', 'A mix of hip-hop', '2020-07-08', 'playlist_136.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (6, 'Chill & Unwind', 'A mix of funk', '2020-08-09', 'playlist_137.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (89, 'Soulful Sundays', 'A mix of classical', '2025-01-14', 'playlist_138.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (13, 'Heavy Rotation', 'A mix of classical', '2020-12-12', 'playlist_139.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (74, 'Coastal Chill', 'A mix of r&b', '2022-12-03', 'playlist_140.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (6, 'Dreamscape', 'A mix of jazz', '2020-11-02', 'playlist_141.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (79, 'Echo Chamber', 'A mix of jazz', '2021-01-04', 'playlist_142.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (95, 'Rainy Day Moods', 'A mix of latin', '2021-06-29', 'playlist_143.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Flow State', 'A mix of soul', '2022-11-19', 'playlist_144.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (1, 'Groove Theory', 'A mix of ambient', '2022-09-18', 'playlist_145.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (2, 'Moonlit Melodies', 'A mix of latin', '2020-06-20', 'playlist_146.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (37, 'Study Focus', 'A mix of ambient', '2024-07-09', 'playlist_147.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (18, 'Flow State', 'A mix of blues', '2021-05-12', 'playlist_148.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (95, 'Voyager Vibes', 'A mix of blues', '2023-09-07', 'playlist_149.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (8, 'Moonlit Melodies', 'A mix of ambient', '2022-06-28', 'playlist_150.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (76, 'Hometown Heroes', 'A mix of electronic', '2024-10-26', 'playlist_151.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (73, 'Groove Theory', 'A mix of country', '2020-07-18', 'playlist_152.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (50, 'Blue Horizon', 'A mix of pop', '2020-07-10', 'playlist_153.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (20, 'Synthwave Dreams', 'A mix of country', '2021-01-01', 'playlist_154.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (6, 'Midnight Drive', 'A mix of latin', '2021-12-09', 'playlist_155.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (59, 'Urban Underground', 'A mix of folk', '2024-11-13', 'playlist_156.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (9, 'Groove Theory', 'A mix of jazz', '2021-10-12', 'playlist_157.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (62, 'Energize', 'A mix of country', '2020-05-27', 'playlist_158.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (92, 'Weekend Vibes', 'A mix of jazz', '2023-07-27', 'playlist_159.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Electric Avenue', 'A mix of indie', '2024-11-28', 'playlist_160.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (84, 'Whispering Waves', 'A mix of reggae', '2022-05-16', 'playlist_161.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (73, 'Soulful Sundays', 'A mix of dance', '2024-11-18', 'playlist_162.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (89, 'Beat Drop', 'A mix of world', '2023-03-23', 'playlist_163.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (6, 'Sonic Sunrise', 'A mix of punk', '2021-11-10', 'playlist_164.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (54, 'Serene Strings', 'A mix of electronic', '2021-04-22', 'playlist_165.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (96, 'Hometown Heroes', 'A mix of country', '2022-08-17', 'playlist_166.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (17, 'Acoustic Mornings', 'A mix of folk', '2021-06-28', 'playlist_167.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (45, 'Serene Strings', 'A mix of country', '2023-02-03', 'playlist_168.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'Electric Avenue', 'A mix of world', '2020-01-25', 'playlist_169.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (71, 'Floating Free', 'A mix of reggae', '2021-02-27', 'playlist_170.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (26, 'Moonlit Melodies', 'A mix of ambient', '2021-01-04', 'playlist_171.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Sunrise Grooves', 'A mix of electronic', '2024-12-16', 'playlist_172.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (1, 'Throwback Jams', 'A mix of classical', '2023-02-15', 'playlist_173.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (18, 'Fresh Finds', 'A mix of pop', '2023-12-13', 'playlist_174.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (27, 'Late-Night Loops', 'A mix of r&b', '2023-01-27', 'playlist_175.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (89, 'Saturday Morning Jazz', 'A mix of metal', '2024-04-17', 'playlist_176.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (66, 'Chill & Unwind', 'A mix of rock', '2020-11-08', 'playlist_177.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (96, 'Hometown Heroes', 'A mix of r&b', '2020-04-14', 'playlist_178.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (58, 'Saturday Morning Jazz', 'A mix of folk', '2022-04-11', 'playlist_179.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (80, 'Velvet Dusk', 'A mix of indie', '2020-10-17', 'playlist_180.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (79, 'Smooth Sailing', 'A mix of country', '2020-02-18', 'playlist_181.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'Urban Underground', 'A mix of jazz', '2022-08-08', 'playlist_182.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (11, 'Saturday Morning Jazz', 'A mix of metal', '2020-03-01', 'playlist_183.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (21, 'Feel-Good Hits', 'A mix of r&b', '2023-06-24', 'playlist_184.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (63, 'Golden Hour', 'A mix of pop', '2020-12-18', 'playlist_185.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (76, 'Floating Free', 'A mix of soul', '2025-02-22', 'playlist_186.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (30, 'Coastal Chill', 'A mix of country', '2023-08-02', 'playlist_187.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (80, 'Velvet Dusk', 'A mix of metal', '2023-10-08', 'playlist_188.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (60, 'Coastal Chill', 'A mix of classical', '2020-06-26', 'playlist_189.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (76, 'Roadtrip Anthems', 'A mix of country', '2025-04-18', 'playlist_190.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (36, 'Aurora Beats', 'A mix of world', '2021-11-09', 'playlist_191.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (35, 'Velvet Lounge', 'A mix of r&b', '2020-03-19', 'playlist_192.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (72, 'City Lights', 'A mix of jazz', '2024-10-21', 'playlist_193.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (34, 'Groove Theory', 'A mix of ambient', '2024-06-17', 'playlist_194.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (38, 'Vintage Vibes', 'A mix of funk', '2024-03-21', 'playlist_195.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (83, 'Flow State', 'A mix of folk', '2024-12-27', 'playlist_196.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (5, 'Roadtrip Anthems', 'A mix of indie', '2024-03-20', 'playlist_197.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (34, 'Heavy Rotation', 'A mix of hip-hop', '2021-07-23', 'playlist_198.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (48, 'Afterglow', 'A mix of blues', '2023-03-19', 'playlist_199.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (56, 'Mystic Rhythms', 'A mix of funk', '2023-11-27', 'playlist_200.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (52, 'Echo Chamber', 'A mix of ambient', '2020-09-29', 'playlist_201.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (67, 'Synthwave Dreams', 'A mix of folk', '2020-09-15', 'playlist_202.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (30, 'Sunshine Serenade', 'A mix of electronic', '2022-10-20', 'playlist_203.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (96, 'Flow State', 'A mix of r&b', '2024-07-11', 'playlist_204.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (76, 'Serene Strings', 'A mix of funk', '2023-08-05', 'playlist_205.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (86, 'Golden Groove', 'A mix of latin', '2022-02-09', 'playlist_206.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (12, 'Cascade Waves', 'A mix of funk', '2022-09-03', 'playlist_207.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (13, 'Fresh Finds', 'A mix of r&b', '2022-04-08', 'playlist_208.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (62, 'Rainy Day Moods', 'A mix of electronic', '2023-06-20', 'playlist_209.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (62, 'Acoustic Mornings', 'A mix of rock', '2021-08-21', 'playlist_210.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (59, 'Serene Strings', 'A mix of indie', '2023-03-25', 'playlist_211.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (84, 'Warm Embrace', 'A mix of indie', '2024-03-08', 'playlist_212.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (72, 'Soulful Sundays', 'A mix of electronic', '2021-11-02', 'playlist_213.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Flow State', 'A mix of classical', '2021-02-20', 'playlist_214.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (56, 'Starlit Skies', 'A mix of world', '2023-10-26', 'playlist_215.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (78, 'Hometown Heroes', 'A mix of world', '2021-12-21', 'playlist_216.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (5, 'Synthwave Dreams', 'A mix of metal', '2020-09-01', 'playlist_217.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (17, 'Ocean Breeze', 'A mix of reggae', '2024-05-16', 'playlist_218.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (65, 'Electric Sunset', 'A mix of hip-hop', '2021-11-02', 'playlist_219.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (70, 'Electric Sunset', 'A mix of pop', '2025-05-02', 'playlist_220.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (64, 'Roadtrip Anthems', 'A mix of indie', '2021-09-17', 'playlist_221.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (37, 'Energize', 'A mix of indie', '2021-02-07', 'playlist_222.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (59, 'Midnight Drive', 'A mix of world', '2023-07-02', 'playlist_223.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (66, 'Tranquil Trails', 'A mix of hip-hop', '2020-01-20', 'playlist_224.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (38, 'Twilight Tones', 'A mix of blues', '2022-11-29', 'playlist_225.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (41, 'Flow State', 'A mix of blues', '2024-09-29', 'playlist_226.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (10, 'Soul Session', 'A mix of latin', '2022-12-28', 'playlist_227.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (83, 'Flow State', 'A mix of funk', '2024-08-12', 'playlist_228.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (12, 'Moonlit Melodies', 'A mix of reggae', '2022-12-16', 'playlist_229.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Heartbeat Highway', 'A mix of country', '2023-05-20', 'playlist_230.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (74, 'Electric Sunset', 'A mix of ambient', '2024-06-04', 'playlist_231.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (96, 'Sunshine Serenade', 'A mix of country', '2020-08-11', 'playlist_232.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (38, 'Sunrise Grooves', 'A mix of funk', '2025-01-08', 'playlist_233.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (23, 'Velvet Lounge', 'A mix of soul', '2020-06-26', 'playlist_234.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Energize', 'A mix of rock', '2021-01-07', 'playlist_235.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (23, 'Soul Session', 'A mix of ambient', '2024-11-21', 'playlist_236.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (74, 'Sunrise Grooves', 'A mix of rock', '2024-04-30', 'playlist_237.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Summer Heat', 'A mix of punk', '2020-10-05', 'playlist_238.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (1, 'Vintage Vibes', 'A mix of reggae', '2021-09-07', 'playlist_239.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (59, 'Velvet Lounge', 'A mix of funk', '2024-09-10', 'playlist_240.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (13, 'Weekend Vibes', 'A mix of jazz', '2020-06-23', 'playlist_241.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (86, 'Neon Nights', 'A mix of dance', '2023-11-05', 'playlist_242.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (24, 'Saturday Morning Jazz', 'A mix of folk', '2024-05-21', 'playlist_243.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (57, 'Energize', 'A mix of dance', '2024-02-12', 'playlist_244.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (54, 'Floating Free', 'A mix of punk', '2024-01-27', 'playlist_245.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (38, 'Feel-Good Hits', 'A mix of country', '2024-05-31', 'playlist_246.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (76, 'Urban Pulse', 'A mix of blues', '2022-02-08', 'playlist_247.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (97, 'Synthwave Dreams', 'A mix of ambient', '2024-08-27', 'playlist_248.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (99, 'Hometown Heroes', 'A mix of hip-hop', '2022-12-27', 'playlist_249.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (46, 'Study Focus', 'A mix of latin', '2022-04-19', 'playlist_250.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (63, 'Midnight Reverie', 'A mix of classical', '2023-11-20', 'playlist_251.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (50, 'Pulse Point', 'A mix of soul', '2023-11-07', 'playlist_252.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (44, 'Ocean Breeze', 'A mix of punk', '2022-07-23', 'playlist_253.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (19, 'Rainy Day Moods', 'A mix of reggae', '2023-11-13', 'playlist_254.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (60, 'Acoustic Mornings', 'A mix of ambient', '2021-04-09', 'playlist_255.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (87, 'Velvet Dusk', 'A mix of jazz', '2022-04-14', 'playlist_256.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (12, 'Coastal Chill', 'A mix of latin', '2021-11-25', 'playlist_257.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (48, 'Saturday Morning Jazz', 'A mix of hip-hop', '2022-04-15', 'playlist_258.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (31, 'Vintage Vibes', 'A mix of country', '2025-01-27', 'playlist_259.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (19, 'Soul Session', 'A mix of soul', '2024-09-30', 'playlist_260.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (71, 'Serene Strings', 'A mix of latin', '2021-11-16', 'playlist_261.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'Secret Stash', 'A mix of classical', '2024-11-02', 'playlist_262.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (26, 'Rooftop Rhythms', 'A mix of indie', '2021-01-16', 'playlist_263.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (7, 'Roadtrip Anthems', 'A mix of soul', '2025-01-24', 'playlist_264.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (17, 'Blue Horizon', 'A mix of electronic', '2023-12-30', 'playlist_265.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (28, 'Rhythm & Hues', 'A mix of r&b', '2021-07-28', 'playlist_266.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (78, 'Neon Nights', 'A mix of blues', '2021-03-26', 'playlist_267.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (83, 'Lazy Afternoon', 'A mix of funk', '2022-02-16', 'playlist_268.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (33, 'Kaleidoscope', 'A mix of dance', '2022-08-09', 'playlist_269.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (48, 'Soul Session', 'A mix of ambient', '2023-01-02', 'playlist_270.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (46, 'Cascade Waves', 'A mix of blues', '2024-04-04', 'playlist_271.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (1, 'Coastal Chill', 'A mix of hip-hop', '2024-07-06', 'playlist_272.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (41, 'Velvet Lounge', 'A mix of classical', '2021-09-06', 'playlist_273.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (34, 'Tranquil Trails', 'A mix of latin', '2021-11-12', 'playlist_274.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (94, 'Urban Underground', 'A mix of metal', '2020-01-31', 'playlist_275.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (62, 'Late-Night Loops', 'A mix of dance', '2020-12-09', 'playlist_276.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (22, 'Midnight Reverie', 'A mix of soul', '2021-04-28', 'playlist_277.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (8, 'Saturday Morning Jazz', 'A mix of folk', '2025-05-13', 'playlist_278.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (79, 'Velvet Lounge', 'A mix of ambient', '2022-06-02', 'playlist_279.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (47, 'Electric Avenue', 'A mix of pop', '2024-11-17', 'playlist_280.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (39, 'Midnight Reverie', 'A mix of r&b', '2021-12-31', 'playlist_281.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (16, 'Warm Embrace', 'A mix of blues', '2023-10-01', 'playlist_282.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (42, 'Weekend Vibes', 'A mix of soul', '2020-11-10', 'playlist_283.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (82, 'Vintage Vibes', 'A mix of hip-hop', '2020-03-05', 'playlist_284.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (49, 'Electric Sunset', 'A mix of rock', '2024-12-28', 'playlist_285.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (30, 'Chill & Unwind', 'A mix of r&b', '2023-10-26', 'playlist_286.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (8, 'Sunrise Grooves', 'A mix of punk', '2022-03-18', 'playlist_287.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (97, 'Golden Groove', 'A mix of metal', '2020-05-18', 'playlist_288.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'Summer Heat', 'A mix of jazz', '2022-01-16', 'playlist_289.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (73, 'Cascade Waves', 'A mix of funk', '2023-03-07', 'playlist_290.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (78, 'Aurora Beats', 'A mix of world', '2022-04-19', 'playlist_291.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (24, 'Midnight Drive', 'A mix of pop', '2021-08-18', 'playlist_292.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (58, 'Sunrise Grooves', 'A mix of jazz', '2023-09-02', 'playlist_293.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (25, 'Midnight Drive', 'A mix of pop', '2024-02-29', 'playlist_294.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'Serene Strings', 'A mix of ambient', '2024-08-18', 'playlist_295.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (20, 'Groove Theory', 'A mix of electronic', '2023-06-05', 'playlist_296.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (35, 'Funky Fusion', 'A mix of indie', '2024-03-12', 'playlist_297.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (90, 'Electric Avenue', 'A mix of country', '2021-01-26', 'playlist_298.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (39, 'Groove Theory', 'A mix of indie', '2020-12-14', 'playlist_299.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (78, 'Synthwave Dreams', 'A mix of indie', '2020-04-29', 'playlist_300.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (8, 'Fresh Finds', 'A mix of folk', '2021-04-10', 'playlist_301.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (80, 'Beat Drop', 'A mix of dance', '2022-09-12', 'playlist_302.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (68, 'Rainy Day Moods', 'A mix of metal', '2023-06-06', 'playlist_303.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (84, 'Serene Strings', 'A mix of jazz', '2023-07-07', 'playlist_304.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (1, 'Late-Night Loops', 'A mix of pop', '2024-01-12', 'playlist_305.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (23, 'Afterglow', 'A mix of jazz', '2020-01-18', 'playlist_306.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (79, 'Rooftop Rhythms', 'A mix of world', '2022-05-01', 'playlist_307.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (34, 'Throwback Jams', 'A mix of ambient', '2021-04-09', 'playlist_308.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (43, 'Cosmic Drift', 'A mix of world', '2024-09-04', 'playlist_309.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (3, 'High Tide', 'A mix of reggae', '2024-09-01', 'playlist_310.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (51, 'Vintage Vibes', 'A mix of funk', '2021-12-16', 'playlist_311.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (52, 'Electric Sunset', 'A mix of indie', '2023-07-01', 'playlist_312.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (41, 'Cascade Waves', 'A mix of jazz', '2024-09-18', 'playlist_313.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (19, 'Weekend Vibes', 'A mix of electronic', '2022-08-31', 'playlist_314.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (55, 'Golden Hour', 'A mix of reggae', '2021-10-12', 'playlist_315.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (40, 'Lazy Afternoon', 'A mix of reggae', '2024-05-26', 'playlist_316.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (41, 'Study Focus', 'A mix of dance', '2022-02-05', 'playlist_317.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (38, 'Ocean Breeze', 'A mix of dance', '2021-08-20', 'playlist_318.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (40, 'Serene Strings', 'A mix of r&b', '2023-08-07', 'playlist_319.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (90, 'High Tide', 'A mix of country', '2024-12-12', 'playlist_320.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (62, 'Heartbeat Highway', 'A mix of country', '2022-11-03', 'playlist_321.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (6, 'Soul Session', 'A mix of indie', '2023-05-23', 'playlist_322.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (47, 'Dreamscape', 'A mix of reggae', '2023-07-27', 'playlist_323.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (95, 'City Lights', 'A mix of country', '2020-05-24', 'playlist_324.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (52, 'Throwback Jams', 'A mix of reggae', '2020-03-14', 'playlist_325.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (48, 'Desert Winds', 'A mix of latin', '2020-10-12', 'playlist_326.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (35, 'Sunrise Grooves', 'A mix of country', '2024-11-14', 'playlist_327.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (68, 'Ocean Breeze', 'A mix of punk', '2024-01-27', 'playlist_328.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (37, 'Acoustic Mornings', 'A mix of latin', '2024-09-19', 'playlist_329.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (3, 'Coastal Chill', 'A mix of dance', '2020-01-03', 'playlist_330.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (59, 'Golden Groove', 'A mix of pop', '2022-05-29', 'playlist_331.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (77, 'Roaming Beats', 'A mix of rock', '2022-07-10', 'playlist_332.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (97, 'Vintage Vibes', 'A mix of classical', '2023-03-07', 'playlist_333.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (64, 'Afterglow', 'A mix of dance', '2023-01-07', 'playlist_334.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (11, 'Velvet Lounge', 'A mix of ambient', '2022-02-25', 'playlist_335.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (12, 'Heavy Rotation', 'A mix of indie', '2024-11-22', 'playlist_336.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (98, 'Coastal Chill', 'A mix of soul', '2022-07-10', 'playlist_337.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (30, 'Afterglow', 'A mix of country', '2023-12-07', 'playlist_338.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (27, 'Velvet Dusk', 'A mix of reggae', '2023-04-09', 'playlist_339.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (44, 'Warm Embrace', 'A mix of rock', '2022-07-25', 'playlist_340.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (20, 'Dreamscape', 'A mix of electronic', '2021-08-06', 'playlist_341.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (6, 'Neon Canvas', 'A mix of metal', '2025-05-03', 'playlist_342.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (98, 'Lush Landscapes', 'A mix of metal', '2024-07-28', 'playlist_343.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (34, 'Summer Heat', 'A mix of indie', '2024-04-24', 'playlist_344.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (38, 'Summer Heat', 'A mix of world', '2020-08-09', 'playlist_345.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (31, 'Cascade Waves', 'A mix of classical', '2020-01-23', 'playlist_346.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (96, 'Heartbeat Highway', 'A mix of hip-hop', '2025-01-10', 'playlist_347.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (24, 'Synthwave Dreams', 'A mix of r&b', '2021-09-22', 'playlist_348.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (83, 'Electric Sunset', 'A mix of electronic', '2023-11-30', 'playlist_349.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (4, 'Late-Night Loops', 'A mix of latin', '2022-05-28', 'playlist_350.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (70, 'Warm Embrace', 'A mix of hip-hop', '2020-06-18', 'playlist_351.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (10, 'Urban Pulse', 'A mix of pop', '2021-10-04', 'playlist_352.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (64, 'Late-Night Loops', 'A mix of dance', '2024-03-10', 'playlist_353.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (67, 'Velvet Dusk', 'A mix of pop', '2021-05-31', 'playlist_354.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (99, 'Saturday Morning Jazz', 'A mix of blues', '2020-10-25', 'playlist_355.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (20, 'Feel-Good Hits', 'A mix of hip-hop', '2020-09-11', 'playlist_356.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (75, 'Late-Night Loops', 'A mix of jazz', '2023-07-22', 'playlist_357.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (62, 'Roadtrip Anthems', 'A mix of pop', '2021-08-02', 'playlist_358.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (21, 'Fresh Finds', 'A mix of reggae', '2021-06-23', 'playlist_359.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (3, 'Serene Strings', 'A mix of latin', '2020-04-28', 'playlist_360.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (38, 'Midnight Drive', 'A mix of punk', '2022-01-25', 'playlist_361.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (87, 'Dreamscape', 'A mix of punk', '2022-01-13', 'playlist_362.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (64, 'Late-Night Loops', 'A mix of jazz', '2021-07-28', 'playlist_363.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (11, 'Heartbeat Highway', 'A mix of r&b', '2025-01-08', 'playlist_364.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (42, 'Moonlit Melodies', 'A mix of jazz', '2024-10-09', 'playlist_365.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (9, 'Synthwave Dreams', 'A mix of ambient', '2024-05-04', 'playlist_366.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (69, 'Neon Nights', 'A mix of country', '2020-09-26', 'playlist_367.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (76, 'Summer Heat', 'A mix of electronic', '2020-11-19', 'playlist_368.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (22, 'City Lights', 'A mix of indie', '2022-06-13', 'playlist_369.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (38, 'Velvet Lounge', 'A mix of metal', '2022-07-23', 'playlist_370.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (17, 'Afterglow', 'A mix of r&b', '2023-09-05', 'playlist_371.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (52, 'Heartbeat Highway', 'A mix of soul', '2022-09-19', 'playlist_372.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (36, 'Rhythm & Hues', 'A mix of funk', '2024-03-17', 'playlist_373.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (56, 'Coastal Chill', 'A mix of jazz', '2025-04-13', 'playlist_374.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (26, 'Sonic Sunrise', 'A mix of hip-hop', '2024-07-18', 'playlist_375.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (80, 'Ember Glow', 'A mix of latin', '2021-03-25', 'playlist_376.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (6, 'Neon Nights', 'A mix of metal', '2023-09-18', 'playlist_377.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (27, 'Soulful Sundays', 'A mix of classical', '2024-05-24', 'playlist_378.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (36, 'Twilight Tones', 'A mix of classical', '2020-12-23', 'playlist_379.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (8, 'Velvet Dusk', 'A mix of pop', '2020-04-18', 'playlist_380.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (73, 'Soul Session', 'A mix of pop', '2024-02-12', 'playlist_381.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (62, 'Flow State', 'A mix of latin', '2023-03-25', 'playlist_382.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (46, 'City Lights', 'A mix of electronic', '2020-07-19', 'playlist_383.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (82, 'City Lights', 'A mix of jazz', '2023-08-11', 'playlist_384.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (40, 'Beat Drop', 'A mix of classical', '2022-12-13', 'playlist_385.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'Summer Heat', 'A mix of reggae', '2021-09-04', 'playlist_386.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'Late-Night Loops', 'A mix of dance', '2023-11-01', 'playlist_387.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (48, 'Voyager Vibes', 'A mix of rock', '2022-06-01', 'playlist_388.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (13, 'Acoustic Mornings', 'A mix of hip-hop', '2024-02-12', 'playlist_389.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (80, 'Echo Chamber', 'A mix of electronic', '2022-10-15', 'playlist_390.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (31, 'Kaleidoscope', 'A mix of funk', '2020-05-31', 'playlist_391.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (90, 'Tranquil Trails', 'A mix of dance', '2021-05-30', 'playlist_392.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (37, 'Throwback Jams', 'A mix of dance', '2020-10-07', 'playlist_393.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (11, 'Tranquil Trails', 'A mix of reggae', '2020-04-11', 'playlist_394.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (12, 'Kaleidoscope', 'A mix of dance', '2022-12-31', 'playlist_395.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (97, 'Morning Dew', 'A mix of rock', '2022-04-19', 'playlist_396.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (66, 'Midnight Drive', 'A mix of blues', '2020-06-25', 'playlist_397.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (52, 'Dreamscape', 'A mix of soul', '2023-12-06', 'playlist_398.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (14, 'Hometown Heroes', 'A mix of punk', '2022-02-12', 'playlist_399.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'Golden Hour', 'A mix of world', '2022-06-23', 'playlist_400.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (88, 'Golden Hour', 'A mix of punk', '2023-08-29', 'playlist_401.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (44, 'Secret Stash', 'A mix of reggae', '2024-11-13', 'playlist_402.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (41, 'Golden Hour', 'A mix of electronic', '2021-09-20', 'playlist_403.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (18, 'Energize', 'A mix of punk', '2020-10-31', 'playlist_404.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (25, 'Moonlit Melodies', 'A mix of electronic', '2022-08-01', 'playlist_405.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (67, 'Kaleidoscope', 'A mix of hip-hop', '2025-04-23', 'playlist_406.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (88, 'Velvet Dusk', 'A mix of rock', '2025-02-18', 'playlist_407.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (32, 'Vintage Vibes', 'A mix of funk', '2023-02-16', 'playlist_408.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (63, 'Rhythm & Hues', 'A mix of funk', '2023-04-19', 'playlist_409.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (69, 'Late-Night Loops', 'A mix of indie', '2023-04-08', 'playlist_410.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (68, 'Beat Drop', 'A mix of country', '2025-02-16', 'playlist_411.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (66, 'Lazy Afternoon', 'A mix of country', '2023-11-01', 'playlist_412.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (22, 'Moonlit Melodies', 'A mix of country', '2020-10-21', 'playlist_413.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (29, 'Soul Session', 'A mix of blues', '2022-03-28', 'playlist_414.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (15, 'Beat Drop', 'A mix of rock', '2025-04-10', 'playlist_415.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (29, 'Twilight Tones', 'A mix of punk', '2020-12-30', 'playlist_416.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (84, 'Twilight Tones', 'A mix of classical', '2023-10-23', 'playlist_417.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (66, 'Golden Groove', 'A mix of jazz', '2024-12-04', 'playlist_418.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (77, 'Ocean Breeze', 'A mix of rock', '2025-03-19', 'playlist_419.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (39, 'Summer Heat', 'A mix of rock', '2021-01-12', 'playlist_420.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (3, 'Velvet Dusk', 'A mix of r&b', '2023-02-24', 'playlist_421.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (44, 'Groove Theory', 'A mix of blues', '2020-09-06', 'playlist_422.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (23, 'Kaleidoscope', 'A mix of pop', '2022-08-06', 'playlist_423.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (32, 'Groove Theory', 'A mix of funk', '2022-01-29', 'playlist_424.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (40, 'Voyager Vibes', 'A mix of classical', '2023-10-07', 'playlist_425.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (90, 'Lush Landscapes', 'A mix of reggae', '2024-04-10', 'playlist_426.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (95, 'Afterglow', 'A mix of indie', '2024-07-08', 'playlist_427.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (39, 'Midnight Drive', 'A mix of rock', '2024-11-01', 'playlist_428.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (60, 'Sunshine Serenade', 'A mix of rock', '2024-09-03', 'playlist_429.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (29, 'City Lights', 'A mix of hip-hop', '2021-01-17', 'playlist_430.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (50, 'Study Focus', 'A mix of soul', '2022-05-12', 'playlist_431.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (63, 'Synthwave Dreams', 'A mix of rock', '2020-12-02', 'playlist_432.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (49, 'Soulful Sundays', 'A mix of dance', '2023-06-15', 'playlist_433.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (91, 'Midnight Reverie', 'A mix of folk', '2023-04-13', 'playlist_434.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (93, 'Blue Horizon', 'A mix of classical', '2024-03-15', 'playlist_435.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (79, 'Heartbeat Highway', 'A mix of country', '2024-04-17', 'playlist_436.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (77, 'Starlit Skies', 'A mix of jazz', '2020-09-11', 'playlist_437.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (18, 'High Tide', 'A mix of funk', '2020-11-20', 'playlist_438.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (54, 'Feel-Good Hits', 'A mix of classical', '2022-11-02', 'playlist_439.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (100, 'Urban Pulse', 'A mix of rock', '2023-02-09', 'playlist_440.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (2, 'Midnight Drive', 'A mix of blues', '2022-12-30', 'playlist_441.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (65, 'Tranquil Trails', 'A mix of metal', '2020-03-20', 'playlist_442.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (37, 'High Tide', 'A mix of metal', '2021-05-15', 'playlist_443.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (60, 'Heartbeat Highway', 'A mix of indie', '2023-09-05', 'playlist_444.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (90, 'Desert Winds', 'A mix of jazz', '2021-10-29', 'playlist_445.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (19, 'Starlit Skies', 'A mix of hip-hop', '2024-01-03', 'playlist_446.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (8, 'Hometown Heroes', 'A mix of blues', '2020-05-03', 'playlist_447.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (40, 'Midnight Reverie', 'A mix of world', '2020-04-29', 'playlist_448.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (33, 'Fresh Finds', 'A mix of folk', '2025-02-04', 'playlist_449.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (5, 'Soul Session', 'A mix of ambient', '2020-08-26', 'playlist_450.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (6, 'Flow State', 'A mix of metal', '2024-03-20', 'playlist_451.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (62, 'Sunrise Grooves', 'A mix of dance', '2022-07-17', 'playlist_452.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (17, 'Soul Session', 'A mix of hip-hop', '2021-02-12', 'playlist_453.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (83, 'Acoustic Mornings', 'A mix of latin', '2022-03-19', 'playlist_454.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (70, 'Lush Landscapes', 'A mix of pop', '2024-10-19', 'playlist_455.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (15, 'Golden Hour', 'A mix of funk', '2020-12-17', 'playlist_456.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (53, 'Warm Embrace', 'A mix of electronic', '2023-03-09', 'playlist_457.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (84, 'Serene Strings', 'A mix of pop', '2024-04-01', 'playlist_458.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (84, 'Throwback Jams', 'A mix of pop', '2020-04-09', 'playlist_459.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (45, 'Secret Stash', 'A mix of ambient', '2022-10-10', 'playlist_460.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (85, 'Sunshine Serenade', 'A mix of punk', '2021-08-27', 'playlist_461.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (42, 'Rainy Day Moods', 'A mix of funk', '2023-12-08', 'playlist_462.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (30, 'Secret Stash', 'A mix of metal', '2025-03-16', 'playlist_463.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (93, 'Saturday Morning Jazz', 'A mix of electronic', '2021-05-13', 'playlist_464.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (71, 'Heartbeat Highway', 'A mix of latin', '2023-11-02', 'playlist_465.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (58, 'Rainy Day Moods', 'A mix of metal', '2024-06-23', 'playlist_466.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (69, 'Sonic Sunrise', 'A mix of reggae', '2023-12-06', 'playlist_467.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (97, 'Serene Strings', 'A mix of r&b', '2024-12-25', 'playlist_468.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (24, 'Saturday Morning Jazz', 'A mix of latin', '2020-02-17', 'playlist_469.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (20, 'Golden Groove', 'A mix of hip-hop', '2021-03-15', 'playlist_470.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (23, 'Flow State', 'A mix of funk', '2021-12-12', 'playlist_471.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Velvet Dusk', 'A mix of rock', '2021-09-16', 'playlist_472.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (61, 'Sunshine Serenade', 'A mix of latin', '2024-03-11', 'playlist_473.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (34, 'Kaleidoscope', 'A mix of metal', '2024-04-28', 'playlist_474.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (87, 'Neon Canvas', 'A mix of blues', '2020-02-20', 'playlist_475.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (40, 'Moonlit Melodies', 'A mix of punk', '2021-11-19', 'playlist_476.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (14, 'Electric Sunset', 'A mix of metal', '2025-01-14', 'playlist_477.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (46, 'Late-Night Loops', 'A mix of dance', '2023-07-05', 'playlist_478.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (72, 'Energize', 'A mix of dance', '2024-08-14', 'playlist_479.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (18, 'Cosmic Drift', 'A mix of metal', '2024-10-16', 'playlist_480.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (73, 'Warm Embrace', 'A mix of electronic', '2024-08-11', 'playlist_481.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (14, 'Desert Winds', 'A mix of blues', '2023-08-21', 'playlist_482.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (86, 'Desert Winds', 'A mix of reggae', '2022-03-25', 'playlist_483.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (98, 'Acoustic Mornings', 'A mix of blues', '2022-04-20', 'playlist_484.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (59, 'Groove Theory', 'A mix of blues', '2024-06-13', 'playlist_485.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (92, 'Neon Canvas', 'A mix of electronic', '2023-09-15', 'playlist_486.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (89, 'Rooftop Rhythms', 'A mix of hip-hop', '2023-11-16', 'playlist_487.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (51, 'Floating Free', 'A mix of punk', '2021-09-07', 'playlist_488.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (82, 'Funky Fusion', 'A mix of funk', '2020-06-04', 'playlist_489.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (3, 'Neon Canvas', 'A mix of ambient', '2021-03-06', 'playlist_490.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (45, 'Urban Pulse', 'A mix of indie', '2020-02-02', 'playlist_491.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (24, 'Kaleidoscope', 'A mix of pop', '2023-07-02', 'playlist_492.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (59, 'Hometown Heroes', 'A mix of blues', '2022-10-05', 'playlist_493.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (28, 'Rainy Day Moods', 'A mix of dance', '2022-05-31', 'playlist_494.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (93, 'Electric Sunset', 'A mix of classical', '2022-11-08', 'playlist_495.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (19, 'Weekend Vibes', 'A mix of ambient', '2021-01-11', 'playlist_496.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (8, 'Roaming Beats', 'A mix of dance', '2021-11-17', 'playlist_497.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (18, 'Echo Chamber', 'A mix of electronic', '2025-01-28', 'playlist_498.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (52, 'Serene Strings', 'A mix of punk', '2021-06-04', 'playlist_499.jpg');
INSERT INTO PLAYLISTS (user_id, title, description, date_created, image) VALUES (67, 'Cosmic Drift', 'A mix of pop', '2022-05-28', 'playlist_500.jpg');
